LightBDD/LightBDD

LightBDD/Configuration/LightBDDConfiguration.cs
LightBDD/Configuration/WriterElement.cs
LightBDD/Coordination/SummaryGeneratorFactory.cs
LightBDD/LightBDD.csproj
LightBDD/SummaryGeneration/SummaryFileWriterCurrentDate.cs

I would like to have a new feature to customize the name of the outputPath. I want to drop the file to a network folder and adding the date in the name (or the name of a folder).
Exemple :
\\SharedFolder\Report\{0:yyyy-MM-dd}\MyReport_{0:HH_mm_ss}.html

Add a second SummaryWriter to add date in the outputPath.

---

Changelog.txt
src/LightBDD.Framework/Reporting/Configuration/ReportWritersConfiguration.cs
test/LightBDD.AcceptanceTests/ConfiguredLightBddScopeAttribute.cs
test/LightBDD.AcceptanceTests/Features/HTML_report_feature.Steps.cs
test/LightBDD.Framework.Reporting.UnitTests/Formatters/XmlReportFormatter_tests.cs
test/LightBDD.Framework.Reporting.UnitTests/ReportFileWriter_formattable_path_tests.cs
test/LightBDD.Framework.Reporting.UnitTests/ReportFileWriter_tests.cs

The directory separator is hardcoded for Win systems and does not work on Unix based systems. So instead of using a double backslash use the System.IO.Path.DirectorySeparatorChar.
Issue reference: #87 
Replace all using of the double backslash in paths to create a directory in framework and the corresponding tests.

Directory fix for Unix based systems

---

Changelog.txt
src/LightBDD.Core/Extensibility/CoreMetadataProvider.cs
src/LightBDD.Core/Extensibility/Implementation/NameParser.cs
test/LightBDD.Core.UnitTests/CoreBddRunner_parameterized_step_metadata_collection_tests.cs
test/LightBDD.Framework.UnitTests/Scenarios/Extended/Parameterized_scenario_runner_parameter_capture_tests.cs
test/LightBDD.UnitTests.Helpers/TestableIntegration/TestStep.cs

Issue reference: #92
- Excluded this argument from step name display when extension method is used;
- Corrected parameter placement in name when having appended parameter of lower index than matching in-text replacement at the end of the name, like: `void Step_with_param(string other, string param)`

#92 Excluded this argument from step name display when extension method is used

---

Changelog.txt
examples/Example.LightBDD.MsTest2/README.md
examples/Example.LightBDD.NUnit2/README.md
examples/Example.LightBDD.NUnit3/Example.LightBDD.NUnit3.csproj
examples/Example.LightBDD.NUnit3/README.md
examples/Example.LightBDD.NUnit3/run-dotnet-test.cmd
examples/Example.LightBDD.XUnit2/README.md
src/LightBDD.Framework/Notification/Configuration/FeatureProgressNotifierConfiguration.cs
src/LightBDD.Framework/Notification/Configuration/Implementation/IScenarioProgressNotifierProvider.cs
src/LightBDD.Framework/Notification/Configuration/Implementation/ScenarioProgressNotifierComposer.cs
src/LightBDD.Framework/Notification/Configuration/Implementation/StatefulScenarioProgressNotifierProvider.cs
src/LightBDD.Framework/Notification/Configuration/Implementation/StatelessScenarioProgressNotifierProvider.cs
src/LightBDD.Framework/Notification/Configuration/ScenarioProgressNotifierConfiguration.cs
src/LightBDD.Framework/Notification/DelegatingFeatureProgressNotifier.cs
src/LightBDD.Framework/Notification/DelegatingScenarioProgressNotifier.cs
src/LightBDD.Framework/Notification/Implementation/ParallelProgressNotifier.cs
src/LightBDD.MsTest2/Configuration/TestFrameworkConfigurationExtensions.cs
src/LightBDD.MsTest2/LightBddScope.cs
src/LightBDD.NUnit2/Configuration/TestFrameworkConfigurationExtensions.cs
src/LightBDD.NUnit2/LightBddScopeAttribute.cs
src/LightBDD.NUnit3/Configuration/TestFrameworkConfigurationExtensions.cs
src/LightBDD.NUnit3/Implementation/NUnit3ProgressNotifier.cs
src/LightBDD.NUnit3/LightBddScopeAttribute.cs
src/LightBDD.XUnit2/Configuration/TestFrameworkConfigurationExtensions.cs
src/LightBDD.XUnit2/Implementation/XUnit2ProgressNotifier.cs
src/LightBDD.XUnit2/LightBddScopeAttribute.cs
test/LightBDD.Framework.UnitTests/Notification/Configuration/FeatureProgressNotifierConfiguration_tests.cs
test/LightBDD.Framework.UnitTests/Notification/Configuration/ScenarioProgressNotifierConfiguration_tests.cs
test/LightBDD.Framework.UnitTests/Notification/DelegatingFeatureProgressNotifier_tests.cs
test/LightBDD.Framework.UnitTests/Notification/DelegatingScenarioProgressNotifier_tests.cs

Issue reference: #34
* Implemented immediate progress notification when executed with `dotnet test` or `nunit3-console.exe`
* Simplified scenario summary printed in VisualStudio Test Explorer output / Resharper output and console output for LightBDD.XUnit2
* Added ClearNotifiers() / AppendNotifiers() methods to FeatureProgressNotifierConfiguration in order to simplify combining different notifiers
* Added ClearNotifierProviders() / AppendNotifierProviders() methods to ScenarioProgressNotifierConfiguration in order to simplify combining different notifiers
* Added AppendFrameworkDefaultProgressNotifiers() extensions to FeatureProgressNotifierConfiguration and ScenarioProgressNotifierConfiguration to allow re-applying integration specific notifiers after they has been …

#34 Implemented immediate progress notification for LightBDD.NUnit3 and improved it for other integrations

---

Changelog.txt
LightBDD.sln
examples/Example.LightBDD.XUnit2/ConfiguredLightBddScopeAttribute.cs
src/LightBDD.XUnit2/ClassCollectionBehaviorAttribute.cs
src/LightBDD.XUnit2/Implementation/Customization/AssemblySettings.cs
src/LightBDD.XUnit2/Implementation/Customization/ScenarioTestCaseRunner.cs
src/LightBDD.XUnit2/Implementation/Customization/TaskExecutor.cs
src/LightBDD.XUnit2/Implementation/Customization/TestFrameworkAssemblyRunner.cs
src/LightBDD.XUnit2/Implementation/Customization/TestFrameworkClassRunner.cs
src/LightBDD.XUnit2/Implementation/Customization/TestFrameworkCollectionRunner.cs
src/LightBDD.XUnit2/Implementation/Customization/TestFrameworkExecutor.cs

* Added `ClassCollectionBehaviorAttribute` allowing to enable inter-class test parallelization
the class tests as well as test cases will run in parallel as long as following criteria are met:
* test class does not implement `IClassFixture<T>` interface,
* test class does not implement `ICollectionFixture<T>` interface,
* test class does not have `CollectionAttribute` attribute applied.
Issue reference: #117

#117 Added experimental ClassCollectionBehavior attribute allowing inter-class test parallelization

---

Changelog.txt
src/LightBDD.Framework/State.cs
test/LightBDD.AcceptanceTests/Features/HtmlReportContext.cs
test/LightBDD.Framework.UnitTests/State_tests.cs

Added `State<T>` helper struct for managing uninitialized shared state, offering:
* `IsInitialized` property returning false if state has not been initialized,
* `GetValue()` method retrieving value or throwing meaningful exception for uninitialized state (it's possible to specify the member name that will be included in exception)
* `GetValueOrDefault(T defaultValue = default(T))` method returning default value if state is not initialized or has null value (in case T is reference type),
* implicit conversions from T and to T, allowing code like:
```c#
State<int> _field;
/* ... */
_field = 5; // sets value
/* ... */
int variable = _field; // gets value or throws if not initialized
```
Usage patterns:
1. Simple usage when state is only set or get
```c#
class My_feature: FeatureFixture
{ …
```

I134 Added State<T> helper struct for managing uninitialized shared state

---

Changelog.txt
src/LightBDD.Framework/Reporting/Implementation/FilePathHelper.cs
test/LightBDD.Framework.Reporting.UnitTests/ReportFileWriter_tests.cs

Before the fix it was not possible to specify absolute path for the report files on Linux (see #137 details).
With this fix, the report file paths should properly handle paths starting with directory separator  characters (like `\`, `/`), as well as UNC paths.
Issue reference: #137
|Env|Working dir|Base dir|Output Path|Result|
|--|--|--|--|--|
|Windows|d:\temp|c:\dev\project\bin|~\reports\file.html|c:\dev\project\bin\reports\file.html|
|Windows|d:\temp|c:\dev\project\bin|reports\file.html|d:\temp\reports\file.html|
|Windows|d:\temp|c:\dev\project\bin|\reports\file.html|d:\reports\file.html|
|Windows|d:\temp|c:\dev\project\bin|\\\\machine\reports\file.html|\\\\machine\reports\file.html|
|Windows|d:\temp|c:\dev\project\bin|f:\reports\file.html|f:\reports\file.html| …

#137 Unable to specify absolute path to report location on Linux

---

Changelog.txt
src/LightBDD.Framework/Expectations/ExpectationExtensions.cs
src/LightBDD.Framework/Expectations/Implementation/AndExpectation.cs
src/LightBDD.Framework/Expectations/Implementation/OrExpectation.cs
test/LightBDD.Framework.UnitTests/Expectations/AllTrueExpectation_tests.cs
test/LightBDD.Framework.UnitTests/Expectations/AnyTrueExpectation_tests.cs

Issue reference: #148
* Expect.To.BeAnyTrue<T>() with no sub-expectations should fail
* Rendered `BeAnyTrue(...)` as `any true (...)`
* Rendered `BeAllTrue(...)` as `all true (...)`

#148 Expect.To.BeAnyTrue<T>() with no sub-expectations should fail

---

examples/Example.LightBDD.Fixie2/Example.LightBDD.Fixie2.csproj
src/LightBDD.Fixie2/LightBDD.Fixie2.csproj
test/LightBDD.Fixie2.UnitTests/LightBDD.Fixie2.UnitTests.csproj

Issue reference: #160
* Updated Fixie dependency to v2.0.2 to detect tests in VS 15.8 and higher

#160 Updated Fixie dependency to v2.0.2 to detect tests in VS 15.8 and higher

---

Changelog.txt
src/LightBDD.Core/Formatting/ExceptionFormatting/DefaultExceptionFormatter.cs
test/LightBDD.Autofac.UnitTests/AssemblyInfo.cs
test/LightBDD.Core.UnitTests/AssemblyInfo.cs
test/LightBDD.Core.UnitTests/CoreBddRunner_execution_extension_tests.cs
test/LightBDD.Core.UnitTests/Formatting/ExceptionFormatting/DefaultExceptionFormatter_tests.cs
test/LightBDD.Extensions.DependencyInjection.UnitTests/AssemblyInfo.cs
test/LightBDD.Framework.Reporting.UnitTests/AssemblyInfo.cs
test/LightBDD.Framework.UnitTests/AssemblyInfo.cs
test/LightBDD.Framework.UnitTests/Scenarios/Basic/Basic_scenario_exception_stack_trace_integration_tests.cs
test/LightBDD.Framework.UnitTests/Scenarios/Extended/Extended_scenario_exception_stack_trace_integration_tests.cs
test/LightBDD.Framework.UnitTests/Scenarios/Fluent/Fluent_scenario_exception_stack_trace_integration_tests.cs
test/LightBDD.UnitTests.Helpers/ExceptionAssertExtensions.cs

Issue reference: #163
* Updated DefaultExceptionFormatter to exclude "End of stack trace" lines

#163 Updated DefaultExceptionFormatter to exclude "End of stack trace" lines and fixed tests

---

Changelog.txt
src/LightBDD.Autofac/AutofacContainerExtensions.cs
src/LightBDD.Autofac/Implementation/AutofacContainer.cs
src/LightBDD.Extensions.DependencyInjection/DiContainerExtensions.cs
src/LightBDD.Extensions.DependencyInjection/Implementation/DiContainer.cs
test/LightBDD.Autofac.UnitTests/AutofacContainer_with_builder_tests.cs
test/LightBDD.Autofac.UnitTests/AutofacContainer_with_explicit_container_tests.cs
test/LightBDD.Core.UnitTests/Dependencies/BasicDependencyContainer_tests.cs
test/LightBDD.Extensions.DependencyInjection.UnitTests/MicrosoftDiContainer_custom_containers.cs
test/LightBDD.Extensions.DependencyInjection.UnitTests/MicrosoftDiContainer_with_explicit_container_tests.cs
test/LightBDD.UnitTests.Helpers/ContainerBaseTests.cs

Updated LightBDD.Extensions.DependencyInjection and LightBDD.Autofac to require specifying takeOwnership flag for containers
Issue reference: #187 
* LightBDD.Autofac
* Added `DependencyContainerConfiguration UseAutofac(this DependencyContainerConfiguration configuration, ILifetimeScope container, bool takeOwnership)`
* Obsoleted `DependencyContainerConfiguration UseAutofac(this DependencyContainerConfiguration configuration, ILifetimeScope container)`
* LightBDD.Extensions.DependencyInjection
* Added `DependencyContainerConfiguration UseContainer(this DependencyContainerConfiguration configuration, IServiceProvider serviceProvider, bool takeOwnership)`
* Obsoleted `DependencyContainerConfiguration UseContainer(this DependencyContainerConfiguration configuration, …

#187 Updated LightBDD.Extensions.DependencyInjection and LightBDD.Autofac to require specifying takeOwnership flag for containers

---

Changelog.txt
LightBDD.sln
src/LightBDD.XUnit2/IgnoreScenarioAttribute.cs
src/LightBDD.XUnit2/Implementation/Customization/AssemblySettings.cs
src/LightBDD.XUnit2/Implementation/Customization/ScenarioTestCaseDiscoverer.cs
src/LightBDD.XUnit2/Implementation/Customization/ScenarioTestRunner.cs
src/LightBDD.XUnit2/Implementation/Customization/SkippedDataRowTestCase.cs
src/LightBDD.XUnit2/Implementation/Customization/TestFrameworkExecutor.cs
src/LightBDD.XUnit2/Implementation/TestContextProvider.cs
src/LightBDD.XUnit2/Implementation/TestSkippedDecorator.cs
src/LightBDD.XUnit2/LightBddScopeAttribute.cs
src/LightBDD.XUnit2/ScenarioAttribute.cs
src/LightBDD.XUnit2/UseXUnitSkipBehaviorAttribute.cs
test/LightBDD.XUnit2.IntegrationTests/Helpers/ConfiguredLightBDDScope.cs
test/LightBDD.XUnit2.IntegrationTests/Helpers/RunScenariosFirst.cs
test/LightBDD.XUnit2.IntegrationTests/Helpers/ScenarioProgressCapture.cs
test/LightBDD.XUnit2.IntegrationTests/LightBDD.XUnit2.IntegrationTests.csproj
test/LightBDD.XUnit2.IntegrationTests/Skipped_scenarios.cs
test/LightBDD.XUnit2.UnitTests/IntegrationTests.cs

Updated LightBDD.XUnit2 to recognize Skip property on Scenario and InlineData attributes 
Added option to fallback to xunit behavior
Issue reference: #185
* Updated LightBDD to support `Skip` property on `ScenarioAttribute` as well as `InlineDataAttribute`, allow the test to run but make it ignored as soon as executed with `Runner`, so that outcome is included in the reports
* Added `UseXUnitSkipBehaviorAttribute` that could enforce default xunit behavior. 
The tests no longer fail when `[InlineData]` is used with `Skip` property.
The feature has been tested in:
* VS Test Explorer (VS 2019 16.3.1)
* Resharper
* dotnet test command

#185 Updated LightBDD.XUnit2 to recognize Skip property on Scenario and InlineData attributes 

---

Changelog.txt
src/LightBDD.Core/Execution/Implementation/RunnableScenario.cs
src/LightBDD.Core/Execution/Implementation/RunnableStep.cs
src/LightBDD.Core/Extensibility/Implementation/ScenarioBuilder.cs
src/LightBDD.Core/Extensibility/StepDescriptor.cs
src/LightBDD.Core/Formatting/Values/IConditionalValueFormatter.cs
src/LightBDD.Framework/Scenarios/Implementation/BasicStepCompiler.cs
src/LightBDD.Framework/Scenarios/Implementation/ExtendedStepCompiler.cs
test/LightBDD.Core.UnitTests/CoreBddRunner_invalid_step_handling_tests.cs
test/LightBDD.Core.UnitTests/CoreBddRunner_parameterized_step_metadata_collection_tests.cs
test/LightBDD.Core.UnitTests/CoreBddRunner_step_execution_with_context_tests.cs
test/LightBDD.Core.UnitTests/Extensibility/StepDescriptor_tests.cs
test/LightBDD.Framework.UnitTests/Scenarios/Basic/Basic_scenario_runner_tests.cs
test/LightBDD.Framework.UnitTests/Scenarios/Extended/Extended_scenario_runner_hierarchical_execution_tests.cs
test/LightBDD.Framework.UnitTests/Scenarios/Extended/Extended_scenario_runner_parameter_capture_tests.cs

Deferred basic and extended step parsing issues escalation to scenario / sub-step run, allowing users to see the the details about other steps and identify problematic steps easier.
Issue reference: #182  
List of changes:  
* Implemented `StepDescriptor.CreateInvalid(Exception ex)` for creating step descriptors that failed to initialize,
* Updated basic and extended step compilers to create invalid descriptors instead of throwing upon parsing failure,
* Updated scenarios and composite-steps to fail fast if any of step-descriptor is invalid. 
```c#
[Scenario]
public async Task My_scenario()
{
await Runner
.AddSteps(_ => Given_some_step())
.AddSteps(() => When_some_step())
.AddSteps(_ => Then_some_step())
.RunAsync();
}
private void Given_some_step() { }
private void When_some_step() { } …
```

#182 Updated basic and extended step parsing to make parsing issues easily discoverable

---

Changelog.txt
src/LightBDD.Core/Extensibility/CoreMetadataProvider.cs
src/LightBDD.Core/Extensibility/StepDescriptor.cs
src/LightBDD.Core/Metadata/Implementation/NameInfo.cs
src/LightBDD.Core/Metadata/Implementation/StepNameInfo.cs
src/LightBDD.Framework/Reporting/Formatters/Html/HtmlResultTextWriter.cs
src/LightBDD.Framework/Scenarios/Implementation/CompactStepCompiler.cs
test/LightBDD.Core.UnitTests/CoreBddRunner_invalid_step_handling_tests.cs
test/LightBDD.Core.UnitTests/Extensibility/CoreMetadataProvider_step_type_interpretation_tests.cs
test/LightBDD.Core.UnitTests/Extensibility/CoreMetadataProvider_tests.cs
test/LightBDD.Core.UnitTests/Extensibility/StepDescriptor_tests.cs
test/LightBDD.Core.UnitTests/Helpers/ParameterInfoHelper.cs
test/LightBDD.Core.UnitTests/Metadata/StepNameInfo_tests.cs
test/LightBDD.Framework.Reporting.UnitTests/Formatters/HtmlReportFormatter_tests.cs
test/LightBDD.Framework.UnitTests/Scenarios/Compact/Compact_scenario_runner_tests.cs
test/LightBDD.UnitTests.Helpers/TestResults.cs

Issue reference: #181
* Core changes:
* Updated `StepDescriptor` with configurable `IsNameFormattingRequired` property defaulting to `true` for descriptors made from `MethodBase` and `false` for pure text-based descriptors,
* Ensured the `StepDescriptor` cannot be made from text having control characters (`char.IsControl()`),
* Updated `CoreMetadataProvider.GetStepName()` to honor `StepDescriptor.IsNameFormattingRequired` when formatting names,
* Framework changes:
* Updated compact steps to trim step names, replace `\t` and `new line` characters with space and remove any other control characters
* Ensured that compact steps does not formats the step names (no `_` replacements)
* Corrected HTML reports to properly render compact step name/step type (escaping html codes)

#181 Improved compact steps parsing and rendering

---

Changelog.txt
src/LightBDD.Autofac/LightBDD.Autofac.csproj
src/LightBDD.Core/LightBDD.Core.csproj
src/LightBDD.Fixie2/LightBDD.Fixie2.csproj
src/LightBDD.Framework/LightBDD.Framework.csproj
src/LightBDD.MsTest2/LightBDD.MsTest2.csproj
src/LightBDD.NUnit3/LightBDD.NUnit3.csproj
src/LightBDD.XUnit2/LightBDD.XUnit2.csproj

Issue reference: #206
* Added netstandard2.0 to all LightBdd packages

#206 Add explicit netstandard2.0 for packages to decrease dependency graph

---

Changelog.txt
src/LightBDD.Framework/Scenarios/ContextualExtensions.cs
test/LightBDD.Framework.UnitTests/Scenarios/Contextual/Contextual_runner_tests.cs

Issue reference: #214
- Added IBddRunner.WithContext() overloads with resolver and onConfigure function

#214 Added IBddRunner.WithContext() overloads with resolver and onConfigure function

---

Changelog.txt
src/LightBDD.Framework/Resources/ResourcePool.cs
test/LightBDD.AcceptanceTests/ConfiguredLightBddScopeAttribute.cs
test/LightBDD.AcceptanceTests/Helpers/ChromeDriverInstaller.cs
test/LightBDD.AcceptanceTests/LightBDD.AcceptanceTests.csproj
test/LightBDD.Framework.UnitTests/Resources/ResourcePool_tests.cs

Issue reference: #231 
- Extended ResourcePool to support async resource factory
- Fixed AcceptanceTests to download proper ChromeDriver
- Fixed AcceptanceTests to dispose ChromeDriver upon creation failure

Fixed ChromeDriver version mismatch in AcceptanceTests

---

Changelog.txt
src/LightBDD.Core/Formatting/Diagnostics/ObjectFormatter.cs
test/LightBDD.Core.UnitTests/Formatting/Diagnostics/ObjectFormatter_tests.cs

…
Issue reference: 
* Updated `ObjectFormatter` to format `DateTime`, `DateTimeOffset` types with `O` format,
* Updated `ObjectFormatter` to format `IFormattable` types with invariant culture

#248 Improved MessageListener.EnsureReceived() to return friendly message dumps for common types

---

Changelog.txt
src/LightBDD.Framework/Expectations/Implementation/CastExpectation.cs
test/LightBDD.Framework.UnitTests/Expectations/CastFromExpectation_tests.cs
test/LightBDD.Framework.UnitTests/Parameters/VerifiableDataTable_tests.cs

Issue reference: #276 
- Fixed casting null to Nullable for CastExpectation

#276 Fixed casting null to Nullable for CastExpectation

---

Changelog.txt
src/LightBDD.Autofac/LightBDD.Autofac.csproj
src/LightBDD.Core/LightBDD.Core.csproj
src/LightBDD.Extensions.DependencyInjection/LightBDD.Extensions.DependencyInjection.csproj
src/LightBDD.Fixie2/LightBDD.Fixie2.csproj
src/LightBDD.NUnit3/LightBDD.NUnit3.csproj
src/LightBDD.XUnit2/LightBDD.XUnit2.csproj
test/LightBDD.MsTest3.UnitTests/LightBDD.MsTest3.UnitTests.csproj

#296 Added net6 target framework to all LightBDD packages

---

Changelog.txt
src/LightBDD.Core/Execution/Coordination/FeatureCoordinator.cs
test/LightBDD.Core.UnitTests/Execution/FeatureCoordinatorTests.cs
test/LightBDD.Core.UnitTests/Execution/FeatureCoordinator_global_initialization_and_teardown_tests.cs

Issue reference: #344
- (LightBDD.Core)(Change) Allowed IReportFormatter and IGlobalResourceSetUp implementations to use LightBDDConfigurationAware base

#344 Allowed IReportFormatter and IGlobalResourceSetUp implementations to use LightBDDConfigurationAware base

---

Changelog.txt
src/LightBDD.Framework/Expectations/ExpectationExtensions.cs
src/LightBDD.Framework/Expectations/Implementation/CastExpectation.cs
src/LightBDD.Framework/Expectations/Implementation/CastHelper.cs
src/LightBDD.Framework/Expectations/Implementation/CastableExpectation.cs
src/LightBDD.Framework/Expectations/Implementation/NumericTypeHelper.cs
src/LightBDD.Framework/Expectations/Implementation/TypeExpectation.cs
src/LightBDD.Framework/LightBDD.Framework.csproj
test/LightBDD.Framework.UnitTests/Expectations/BeCastableTo_tests.cs
test/LightBDD.Framework.UnitTests/Expectations/BeOfType_tests.cs

Issue reference: #357
- Implemented BeOfType<T>() and BeCastableTo<T>()

#357 Implemented BeOfType<T>() and BeCastableTo<T>()

---

Changelog.txt
src/LightBDD.Core/ExecutionContext/Implementation/CurrentStepProperty.cs
src/LightBDD.Core/ExecutionContext/ScenarioExecutionContext.cs
src/LightBDD.Fixie3/StepExecutionExtensions.cs
src/LightBDD.Framework/StepExecution.cs
src/LightBDD.XUnit2/StepExecutionExtensions.cs
test/LightBDD.Core.UnitTests/StepExecution_tests.cs
test/LightBDD.Framework.UnitTests/ExecutionContext/ScenarioExecutionContext_tests.cs
test/LightBDD.UnitTests.Helpers/TestableIntegration/StepExecutionExtensions.cs

Issue reference: #353 
- (LightBDD.Framework)(Change) Changed StepExecution.Current.Bypass() and StepExecution.Current.IgnoreScenario() to validate that they are called within running scenario

Changed StepExecution.Current.Bypass()/IgnoreScenario() to validate that they are called within running scenario

---

Changelog.txt
src/LightBDD.Framework/Expectations/ExpectationExtensions.cs
test/LightBDD.Framework.UnitTests/Expectations/BeLikeExpectation_tests.cs
test/LightBDD.Framework.UnitTests/Expectations/Helpers/ExpectationScenario.cs
test/LightBDD.Framework.UnitTests/Expectations/MatchExpectation_tests.cs

Issue reference: #351
+ Updated Expect.To.BeLike()/BeLikeIgnoreCase() to match multiline text
+ Added Expect.To.Match(string, RegexOptions) overload

#351 Updated Expect.To.BeLike()/BeLikeIgnoreCase() to match multiline text and added Expect.To.Match(string, RegexOptions) overload

---

Changelog.txt
src/LightBDD.Core/Configuration/ExecutionExtensionsConfiguration.cs
src/LightBDD.Core/Execution/Implementation/RunnableScenario.cs
src/LightBDD.Core/Extensibility/Execution/IExecutionExtensions.cs
src/LightBDD.Fixie3/LightBddScope.cs
src/LightBDD.MsTest3/LightBddScope.cs
src/LightBDD.NUnit3/LightBddScopeAttribute.cs
src/LightBDD.XUnit2/LightBddScopeAttribute.cs
test/LightBDD.Core.UnitTests/Configuration/ExecutionExtensionsConfiguration_tests.cs
test/LightBDD.Core.UnitTests/CoreBddRunner_execution_extension_tests.cs
test/LightBDD.Fixie3.UnitTests/ConfiguredLightBddScope.cs
test/LightBDD.Fixie3.UnitTests/LightBddScope_tests.cs
test/LightBDD.MsTest3.UnitTests/LightBddScopeAttribute_tests.cs
test/LightBDD.NUnit3.UnitTests/LightBddScopeAttribute_tests.cs
test/LightBDD.XUnit2.UnitTests/ConfiguredLightBddScope.cs
test/LightBDD.XUnit2.UnitTests/LightBddScopeAttribute_tests.cs

Issue reference: #356 
- (LightBDD.Core)(Change) Captured LightBddScope OnConfigure() failures

#356 Captured LightBddScope OnConfigure() failures

---

src/LightBDD.Framework/Parameters/VerifiableTable.cs

This is needed when using [RetryScenario] because on each retry ActualRows were already set and EnsureActualNotSet() will make the retry fail because "Actual rows have been already specified".
See related https://github.com/LightBDD/LightBDD/issues/257
Issue reference: https://github.com/LightBDD/LightBDD/issues/365

Allow resetting ActualRows to null to avoid "Actual rows have been already specified" when retrying a scenario

---

Changelog.txt
src/LightBDD.Framework/Parameters/Verifiable.cs
src/LightBDD.Framework/Parameters/VerifiableTable.cs
src/LightBDD.Framework/Parameters/VerifiableTree.cs
test/LightBDD.Framework.UnitTests/Parameters/TableValidator_tests.cs
test/LightBDD.Framework.UnitTests/Parameters/VerifiableDataTable_tests.cs
test/LightBDD.Framework.UnitTests/Parameters/VerifiableTree_tests.cs
test/LightBDD.Framework.UnitTests/Parameters/Verifiable_tests.cs

Issue reference: #365
Added ResetActual() method to Verifiable/VerifiableTable/VerifiableTree to allow setting them once more

Added ResetActual() method to Verifiable/VerifiableTable/VerifiableTree to allow setting them once more
